//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamzik
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimaryEntities : DbContext
    {
        public PrimaryEntities()
            : base("name=PrimaryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<PageTest> PageTest { get; set; }
        public virtual DbSet<T_KAMZIK_PAGE> T_KAMZIK_PAGE { get; set; }
        public virtual DbSet<T_KAMZIK_PAGE_REL> T_KAMZIK_PAGE_REL { get; set; }
        public virtual DbSet<T_KAMZIK_SOURCE> T_KAMZIK_SOURCE { get; set; }
        public virtual DbSet<Page> Page { get; set; }
    }
}
