//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamzik
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KAMZIK_SOURCE
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Content { get; set; }
        public int PageId { get; set; }
    
        public virtual T_KAMZIK_PAGE T_KAMZIK_PAGE { get; set; }
    }
}
