//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kamzik
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_KAMZIK_PAGE
    {
        public int Id { get; set; }
        public string SystemName { get; set; }
        public string PageState { get; set; }
        public string PageType { get; set; }
        public Nullable<int> FK_SOURCE_ID { get; set; }
        public Nullable<int> FK_PACKAGES_ID { get; set; }
        public string HierarchyLevel { get; set; }
    }
}
